language: java
install: true
sudo: false

jdk:
  - openjdk8

env:
  global:
    - MVN_VERSION="3.6.3"

before_install:

script:
  - mvn -version
  - mvn -U clean verify

cache:
  directories:
  - $HOME/.m2/repository
   
notifications:
  email: false
